const Icons = {
  HomeLight: 'home',
  HomeDark: 'home-1',
  HomeRoundLight: 'homeRound2',
  HomeRoundDark: 'homeRound1',
  VideoCameraLight: 'iconfinder_outlined_video_4280481',
  VideoCameraDark: 'iconfinder_video-camera_1608458',
  LiveLight: 'live-streaming',
  LiveDark: 'live-streaming-_1_',
  CalendarDark: 'calendar',
  CalendarLight: 'calendar-_1_',
  RadioLight: 'radio',
  RadioDark: 'iconfinder_radio_signal_antenna_broadcast_5402414',
  GlassFilled: 'glass',
  TowerSignal: 'signal',
  Spin360: 'spin3',
  Spin180: 'cw',
  ArrowRightDirectionDark: 'right-dir',
  ArrowDownDirectionDark: 'down-dir',
  ArrowDownDirectionLight: 'down-open',
  ArrowUpDirectionLight: 'up-open',
  ArrowDownCartDark: 'cart-arrow-down',
  Attach: 'attach',
  Search: 'search',
  ToolTip: 'info-circled-alt',
  Clock: 'clock',
};
export default Icons;
